# Generated by Django 4.0.4 on 2022-04-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
    ]
